"""Cambiar columna estado a tipo ENUM

Revision ID: 1c4d9f116ad6
Revises: a1c56d5ee239
Create Date: 2025-11-21 00:20:26.099072

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c4d9f116ad6"
down_revision: Union[str, None] = "a1c56d5ee239"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Eliminar el valor por defecto existente
    op.alter_column("registros_facturacion", "estado", server_default=None)

    # 2. Eliminar la antigua restricción CHECK manual
    op.drop_constraint("chk_estado_registro", "registros_facturacion", type_="check")

    # 3. Crear el nuevo tipo ENUM
    estado_enum = postgresql.ENUM(
        "pendiente",
        "correcto",
        "aceptado_con_errores",
        "incorrecto",
        "duplicado",
        "anulado",
        "factura_inexistente",
        "no_registrado",
        "error_servidor_aeat",
        name="chk_estado_registro_type",
    )
    estado_enum.create(op.get_bind())

    # 4. Alterar la columna usando SQL nativo (con USING si hubiera datos)
    op.execute(
        "ALTER TABLE registros_facturacion "
        "ALTER COLUMN estado TYPE chk_estado_registro_type "
        "USING estado::text::chk_estado_registro_type"
    )

    # 5. Añadir el nuevo valor por defecto compatible con el ENUM
    op.alter_column("registros_facturacion", "estado", server_default="pendiente")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "registros_facturacion",
        "estado",
        existing_type=sa.Enum(
            "PENDIENTE",
            "CORRECTO",
            "ACEPTADO_CON_ERRORES",
            "INCORRECTO",
            "DUPLICADO",
            "ANULADO",
            "FACTURA_INEXISTENTE",
            "NO_REGISTRADO",
            "ERROR_SERVIDOR_AEAT",
            name="chk_estado_registro_type",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'pendiente'::character varying"),
    )
    # Eliminar el tipo ENUM
    op.execute("DROP TYPE chk_estado_registro_type")
    # ### end Alembic commands ###
