"""hacer huella not null

Revision ID: 52d734b1b4ac
Revises:
Create Date: 2025-11-15 15:54:05.987535

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52d734b1b4ac"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "eventos_webhook", "intentos", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "eventos_webhook",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "obligados_tributarios",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "registros_facturacion",
        "huella",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
    )
    op.alter_column(
        "registros_facturacion",
        "intentos_envio",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "registros_facturacion",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "webhooks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhooks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "registros_facturacion",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "registros_facturacion",
        "intentos_envio",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "registros_facturacion",
        "huella",
        existing_type=sa.VARCHAR(length=128),
        nullable=True,
    )
    op.alter_column(
        "obligados_tributarios",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "eventos_webhook",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "eventos_webhook", "intentos", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "api_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
