"""renombrado a xml_respuesta_aeat

Revision ID: 5a7d7845374c
Revises: ef63ad561de7
Create Date: 2025-12-17 05:13:21.826288

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a7d7845374c"
down_revision: Union[str, None] = "ef63ad561de7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registro_facturacion",
        sa.Column(
            "xml_respuesta_aeat",
            sa.Text(),
            nullable=True,
            comment="XML de RespuestaLinea de AEAT para este registro específico",
        ),
    )
    op.drop_column("registro_facturacion", "xml_respuesta")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registro_facturacion",
        sa.Column("xml_respuesta", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("registro_facturacion", "xml_respuesta_aeat")
    # ### end Alembic commands ###
