"""initial_schema

Revision ID: 7a36f91f3438
Revises:
Create Date: 2025-11-26 23:16:05.642708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a36f91f3438"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "colaborador_social",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nif", sa.String(length=20), nullable=False),
        sa.Column("software_name", sa.String(length=255), nullable=False),
        sa.Column("software_version", sa.String(length=50), nullable=False),
        sa.Column("certificate_path", sa.String(length=500), nullable=True),
        sa.Column("certificate_password", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nif"),
    )
    op.create_table(
        "obligado_tributario",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("colaborador_id", sa.Integer(), nullable=False),
        sa.Column("nif", sa.String(length=20), nullable=False),
        sa.Column("nombre_razon_social", sa.String(length=255), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("cert_subject", sa.String(length=500), nullable=True),
        sa.Column("cert_serial", sa.String(length=100), nullable=True),
        sa.Column("cert_valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["colaborador_id"],
            ["colaborador_social.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_obligado_tributario_colaborador_id"),
        "obligado_tributario",
        ["colaborador_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_obligado_tributario_nif"), "obligado_tributario", ["nif"], unique=True
    )
    op.create_table(
        "instalacion_sif",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre_sistema_informatico", sa.String(length=255), nullable=False),
        sa.Column("version_sistema_informatico", sa.String(length=50), nullable=False),
        sa.Column("id_sistema_informatico", sa.String(length=100), nullable=False),
        sa.Column("numero_instalacion", sa.String(length=50), nullable=False),
        sa.Column("cliente_id", sa.String(length=50), nullable=True),
        sa.Column("indicador_multiples_ot", sa.Boolean(), nullable=False),
        sa.Column("obligado_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("certificate_path", sa.String(length=500), nullable=True),
        sa.Column("certificate_password", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["obligado_id"],
            ["obligado_tributario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_key_hash", "instalacion_sif", ["key_hash"], unique=False)
    op.create_index(
        op.f("ix_instalacion_sif_cliente_id"),
        "instalacion_sif",
        ["cliente_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instalacion_sif_key_hash"),
        "instalacion_sif",
        ["key_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_instalacion_sif_obligado_id"),
        "instalacion_sif",
        ["obligado_id"],
        unique=False,
    )
    op.create_table(
        "registro_facturacion",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("instalacion_sif_id", sa.Integer(), nullable=False),
        sa.Column("emisor_nif", sa.String(length=20), nullable=False),
        sa.Column("emisor_nombre", sa.String(length=120), nullable=True),
        sa.Column("serie", sa.String(length=50), nullable=False),
        sa.Column("numero", sa.String(length=50), nullable=False),
        sa.Column("fecha_expedicion", sa.Date(), nullable=False),
        sa.Column("fecha_operacion", sa.Date(), nullable=True),
        sa.Column("destinatario_nif", sa.String(length=20), nullable=True),
        sa.Column("destinatario_nombre", sa.String(length=255), nullable=True),
        sa.Column("tipo_factura", sa.String(length=10), nullable=False),
        sa.Column("tipo_rectificativa", sa.String(length=1), nullable=True),
        sa.Column("operacion", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.String(length=500), nullable=True),
        sa.Column("importe_total", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column("cuota_total", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column(
            "factura_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("huella", sa.String(length=64), nullable=False),
        sa.Column("anterior_huella", sa.String(length=64), nullable=True),
        sa.Column("anterior_emisor_nif", sa.String(length=20), nullable=True),
        sa.Column("anterior_serie", sa.String(length=50), nullable=True),
        sa.Column("anterior_numero", sa.String(length=50), nullable=True),
        sa.Column("anterior_fecha_expedicion", sa.Date(), nullable=True),
        sa.Column("qr_data", sa.Text(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "pendiente",
                "correcto",
                "aceptado_con_errores",
                "incorrecto",
                "duplicado",
                "anulado",
                "factura_inexistente",
                "no_registrado",
                "error_servidor_aeat",
                name="chk_estado_registro_type",
            ),
            server_default="pendiente",
            nullable=False,
        ),
        sa.Column("xml_generado", sa.Text(), nullable=True),
        sa.Column("xml_respuesta", sa.Text(), nullable=True),
        sa.Column(
            "respuesta_aeat", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("codigo_error", sa.String(length=50), nullable=True),
        sa.Column("mensaje_error", sa.Text(), nullable=True),
        sa.Column("intentos_envio", sa.Integer(), nullable=False),
        sa.Column("ultimo_intento_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enviado_aeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instalacion_sif_id"],
            ["instalacion_sif.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instalacion_sif_id",
            "serie",
            "numero",
            "fecha_expedicion",
            name="uq_factura_instalacion",
        ),
    )
    op.create_index(
        "idx_registro_estado_created",
        "registro_facturacion",
        ["estado", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_registro_instalacion_fecha",
        "registro_facturacion",
        ["instalacion_sif_id", "fecha_expedicion"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_anterior_huella"),
        "registro_facturacion",
        ["anterior_huella"],
        unique=True,
    )
    op.create_index(
        op.f("ix_registro_facturacion_emisor_nif"),
        "registro_facturacion",
        ["emisor_nif"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_estado"),
        "registro_facturacion",
        ["estado"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_huella"),
        "registro_facturacion",
        ["huella"],
        unique=True,
    )
    op.create_index(
        op.f("ix_registro_facturacion_instalacion_sif_id"),
        "registro_facturacion",
        ["instalacion_sif_id"],
        unique=False,
    )
    op.create_table(
        "envios_aeat",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("registro_facturacion_id", sa.UUID(), nullable=False),
        sa.Column("intento_numero", sa.Integer(), nullable=False),
        sa.Column("xml_enviado", sa.Text(), nullable=False),
        sa.Column("xml_respuesta", sa.Text(), nullable=True),
        sa.Column(
            "respuesta_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("exitoso", sa.Boolean(), nullable=False),
        sa.Column("codigo_respuesta", sa.String(length=50), nullable=True),
        sa.Column("mensaje_respuesta", sa.Text(), nullable=True),
        sa.Column("tiempo_respuesta_ms", sa.Integer(), nullable=True),
        sa.Column("endpoint_usado", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["registro_facturacion_id"],
            ["registro_facturacion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_envio_registro_intento",
        "envios_aeat",
        ["registro_facturacion_id", "intento_numero"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envios_aeat_registro_facturacion_id"),
        "envios_aeat",
        ["registro_facturacion_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_envios_aeat_registro_facturacion_id"), table_name="envios_aeat"
    )
    op.drop_index("idx_envio_registro_intento", table_name="envios_aeat")
    op.drop_table("envios_aeat")
    op.drop_index(
        op.f("ix_registro_facturacion_instalacion_sif_id"),
        table_name="registro_facturacion",
    )
    op.drop_index(
        op.f("ix_registro_facturacion_huella"), table_name="registro_facturacion"
    )
    op.drop_index(
        op.f("ix_registro_facturacion_estado"), table_name="registro_facturacion"
    )
    op.drop_index(
        op.f("ix_registro_facturacion_emisor_nif"), table_name="registro_facturacion"
    )
    op.drop_index(
        op.f("ix_registro_facturacion_anterior_huella"),
        table_name="registro_facturacion",
    )
    op.drop_index("idx_registro_instalacion_fecha", table_name="registro_facturacion")
    op.drop_index("idx_registro_estado_created", table_name="registro_facturacion")
    op.drop_table("registro_facturacion")
    op.drop_index(op.f("ix_instalacion_sif_obligado_id"), table_name="instalacion_sif")
    op.drop_index(op.f("ix_instalacion_sif_key_hash"), table_name="instalacion_sif")
    op.drop_index(op.f("ix_instalacion_sif_cliente_id"), table_name="instalacion_sif")
    op.drop_index("idx_key_hash", table_name="instalacion_sif")
    op.drop_table("instalacion_sif")
    op.drop_index(op.f("ix_obligado_tributario_nif"), table_name="obligado_tributario")
    op.drop_index(
        op.f("ix_obligado_tributario_colaborador_id"), table_name="obligado_tributario"
    )
    op.drop_table("obligado_tributario")
    op.drop_table("colaborador_social")
    # ### end Alembic commands ###
