"""initial state

Revision ID: 82d845f5a419
Revises:
Create Date: 2025-12-20 03:59:08.104606

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82d845f5a419"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "colaborador_social",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nif", sa.String(length=20), nullable=False),
        sa.Column("software_name", sa.String(length=255), nullable=False),
        sa.Column("software_version", sa.String(length=50), nullable=False),
        sa.Column("certificate_path", sa.String(length=500), nullable=True),
        sa.Column("certificate_password", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nif"),
    )
    op.create_table(
        "obligado_tributario",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("colaborador_id", sa.Integer(), nullable=False),
        sa.Column("nif", sa.String(length=20), nullable=False),
        sa.Column("nombre_razon_social", sa.String(length=255), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("cert_subject", sa.String(length=500), nullable=True),
        sa.Column("cert_serial", sa.String(length=100), nullable=True),
        sa.Column("cert_valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["colaborador_id"],
            ["colaborador_social.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_obligado_tributario_colaborador_id"),
        "obligado_tributario",
        ["colaborador_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_obligado_tributario_nif"), "obligado_tributario", ["nif"], unique=True
    )
    op.create_table(
        "instalacion_sif",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre_sistema_informatico", sa.String(length=255), nullable=False),
        sa.Column("version_sistema_informatico", sa.String(length=50), nullable=False),
        sa.Column("id_sistema_informatico", sa.String(length=100), nullable=False),
        sa.Column("numero_instalacion", sa.String(length=50), nullable=False),
        sa.Column("cliente_id", sa.String(length=50), nullable=True),
        sa.Column("indicador_multiples_ot", sa.Boolean(), nullable=False),
        sa.Column("obligado_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("certificate_path", sa.String(length=500), nullable=True),
        sa.Column("certificate_password", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ultimo_tiempo_espera",
            sa.Integer(),
            nullable=False,
            comment="Último valor 't' recibido de AEAT (en segundos)",
        ),
        sa.Column(
            "ultimo_envio_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Fecha/hora del último envío exitoso a AEAT",
        ),
        sa.Column(
            "registros_pendientes",
            sa.Integer(),
            nullable=False,
            comment="Contador de registros PENDIENTES/ENCOLADOS para esta instalación",
        ),
        sa.ForeignKeyConstraint(
            ["obligado_id"],
            ["obligado_tributario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_instalacion_para_worker",
        "instalacion_sif",
        ["ultimo_envio_at", "ultimo_tiempo_espera", "registros_pendientes"],
        unique=False,
        postgresql_where=sa.text("registros_pendientes > 0"),
    )
    op.create_index(
        op.f("ix_instalacion_sif_cliente_id"),
        "instalacion_sif",
        ["cliente_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instalacion_sif_key_hash"),
        "instalacion_sif",
        ["key_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_instalacion_sif_obligado_id"),
        "instalacion_sif",
        ["obligado_id"],
        unique=False,
    )
    op.create_table(
        "lote_envio",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("instalacion_sif_id", sa.Integer(), nullable=False),
        sa.Column("num_registros", sa.Integer(), nullable=False),
        sa.Column("xml_enviado", sa.Text(), nullable=False),
        sa.Column("xml_respuesta", sa.Text(), nullable=True),
        sa.Column(
            "respuesta_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("codigo_respuesta", sa.String(length=50), nullable=True),
        sa.Column("mensaje_respuesta", sa.Text(), nullable=True),
        sa.Column("tiempo_respuesta_ms", sa.Integer(), nullable=True),
        sa.Column("endpoint_usado", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum(
                "Creado",
                "Encolado",
                "Enviando",
                "Correcto",
                "ParcialmenteCorrecto",
                "Incorrecto",
                "Error",
                "ErrorReintentable",
                name="chk_estado_lote_envio",
            ),
            server_default=sa.text("'Creado'"),
            nullable=False,
        ),
        sa.Column(
            "csv_aeat",
            sa.String(length=64),
            nullable=True,
            comment=(
                "Código Seguro de Verificación devuelto por AEAT (NULL si todos "
                "rechazados)"
            ),
        ),
        sa.Column(
            "tiempo_espera_recibido",
            sa.Integer(),
            nullable=True,
            comment="Valor 't' devuelto por AEAT en esta respuesta (en segundos)",
        ),
        sa.Column(
            "proximo_envio_permitido_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Fecha/hora calculada: created_at + tiempo_espera_recibido",
        ),
        sa.Column(
            "num_registros_enviados",
            sa.Integer(),
            nullable=False,
            comment="Número real de registros incluidos en este lote (máx 1000)",
        ),
        sa.ForeignKeyConstraint(
            ["instalacion_sif_id"],
            ["instalacion_sif.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lote_envio_estado"), "lote_envio", ["estado"], unique=False
    )
    op.create_index(
        op.f("ix_lote_envio_instalacion_sif_id"),
        "lote_envio",
        ["instalacion_sif_id"],
        unique=False,
    )
    op.create_table(
        "outbox_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lote_id", sa.UUID(), nullable=False),
        sa.Column("instalacion_sif_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "Pendiente",
                "Encolado",
                "Procesado",
                "Error",
                name="chk_estado_outbox_event",
            ),
            server_default="Pendiente",
            nullable=False,
        ),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("intentos", sa.Integer(), nullable=False),
        sa.Column("max_intentos", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ultimo_intento_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("procesado_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_mensaje", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["instalacion_sif_id"],
            ["instalacion_sif.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lote_envio.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_outbox_instalacion_estado",
        "outbox_event",
        ["instalacion_sif_id", "estado"],
        unique=False,
    )
    op.create_index(
        "idx_outbox_polling_fifo",
        "outbox_event",
        ["created_at", "id"],
        unique=False,
        postgresql_where=sa.text("estado = 'Pendiente'"),
    )
    op.create_index(
        op.f("ix_outbox_event_created_at"), "outbox_event", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_event_estado"), "outbox_event", ["estado"], unique=False
    )
    op.create_index(op.f("ix_outbox_event_id"), "outbox_event", ["id"], unique=False)
    op.create_index(
        op.f("ix_outbox_event_instalacion_sif_id"),
        "outbox_event",
        ["instalacion_sif_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_event_lote_id"), "outbox_event", ["lote_id"], unique=False
    )
    op.create_table(
        "registro_facturacion",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("instalacion_sif_id", sa.Integer(), nullable=False),
        sa.Column("emisor_nif", sa.String(length=20), nullable=False),
        sa.Column("emisor_nombre", sa.String(length=120), nullable=True),
        sa.Column("serie", sa.String(length=50), nullable=False),
        sa.Column("numero", sa.String(length=50), nullable=False),
        sa.Column("fecha_expedicion", sa.Date(), nullable=False),
        sa.Column("fecha_operacion", sa.Date(), nullable=True),
        sa.Column("destinatario_nif", sa.String(length=20), nullable=True),
        sa.Column("destinatario_nombre", sa.String(length=255), nullable=True),
        sa.Column(
            "tipo_factura",
            sa.Enum(
                "F1", "F2", "F3", "R1", "R2", "R3", "R4", "R5", name="chk_tipo_factura"
            ),
            nullable=False,
        ),
        sa.Column(
            "tipo_rectificativa",
            sa.Enum("S", "I", name="chk_tipo_rectificativa"),
            nullable=True,
        ),
        sa.Column(
            "tipo_operacion",
            sa.Enum("Alta", "Anulacion", name="chk_tipo_operacion"),
            nullable=False,
        ),
        sa.Column("descripcion", sa.String(length=500), nullable=True),
        sa.Column("importe_total", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column("cuota_total", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column(
            "factura_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("huella", sa.String(length=64), nullable=False),
        sa.Column("anterior_huella", sa.String(length=64), nullable=True),
        sa.Column("anterior_emisor_nif", sa.String(length=20), nullable=True),
        sa.Column("anterior_serie", sa.String(length=50), nullable=True),
        sa.Column("anterior_numero", sa.String(length=50), nullable=True),
        sa.Column("anterior_fecha_expedicion", sa.Date(), nullable=True),
        sa.Column("qr_data", sa.Text(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "Pendiente",
                "Encolado",
                "Correcto",
                "AceptadoConErrores",
                "Incorrecto",
                "Duplicado",
                "Anulado",
                "FacturaInexistente",
                "NoRegistrado",
                "ErrorServidorAeat",
                name="chk_estado_registro",
            ),
            server_default=sa.text("'Pendiente'"),
            nullable=False,
        ),
        sa.Column("xml_generado", sa.Text(), nullable=True),
        sa.Column(
            "xml_respuesta_aeat",
            sa.Text(),
            nullable=True,
            comment="XML de RespuestaLinea de AEAT para este registro específico",
        ),
        sa.Column(
            "respuesta_aeat", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("intentos_envio", sa.Integer(), nullable=False),
        sa.Column("ultimo_intento_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enviado_aeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("aeat_codigo_error", sa.Integer(), nullable=True),
        sa.Column("aeat_descripcion_error", sa.String(length=500), nullable=True),
        sa.Column(
            "aeat_duplicado_id_peticion",
            sa.String(length=20),
            nullable=True,
            comment="IdPeticion del registro ya existente en AEAT",
        ),
        sa.Column(
            "aeat_duplicado_estado",
            sa.Enum(
                "Correcta",
                "AceptadaConErrores",
                "Anulada",
                name="chk_estado_duplicado_aeat",
            ),
            nullable=True,
        ),
        sa.Column("aeat_duplicado_codigo_error", sa.Integer(), nullable=True),
        sa.Column("aeat_duplicado_descripcion", sa.String(length=500), nullable=True),
        sa.Column("lote_envio_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instalacion_sif_id"],
            ["instalacion_sif.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lote_envio_id"],
            ["lote_envio.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instalacion_sif_id",
            "serie",
            "numero",
            "fecha_expedicion",
            name="uq_factura_instalacion",
        ),
    )
    op.create_index(
        "idx_registro_estado_created",
        "registro_facturacion",
        ["estado", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_registro_instalacion_fecha",
        "registro_facturacion",
        ["instalacion_sif_id", "fecha_expedicion"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_anterior_huella"),
        "registro_facturacion",
        ["anterior_huella"],
        unique=True,
    )
    op.create_index(
        op.f("ix_registro_facturacion_emisor_nif"),
        "registro_facturacion",
        ["emisor_nif"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_estado"),
        "registro_facturacion",
        ["estado"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_huella"),
        "registro_facturacion",
        ["huella"],
        unique=True,
    )
    op.create_index(
        op.f("ix_registro_facturacion_instalacion_sif_id"),
        "registro_facturacion",
        ["instalacion_sif_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_lote_envio_id"),
        "registro_facturacion",
        ["lote_envio_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_tipo_factura"),
        "registro_facturacion",
        ["tipo_factura"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registro_facturacion_tipo_operacion"),
        "registro_facturacion",
        ["tipo_operacion"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_registro_facturacion_tipo_operacion"),
        table_name="registro_facturacion",
    )
    op.drop_index(
        op.f("ix_registro_facturacion_tipo_factura"), table_name="registro_facturacion"
    )
    op.drop_index(
        op.f("ix_registro_facturacion_lote_envio_id"), table_name="registro_facturacion"
    )
    op.drop_index(
        op.f("ix_registro_facturacion_instalacion_sif_id"),
        table_name="registro_facturacion",
    )
    op.drop_index(
        op.f("ix_registro_facturacion_huella"), table_name="registro_facturacion"
    )
    op.drop_index(
        op.f("ix_registro_facturacion_estado"), table_name="registro_facturacion"
    )
    op.drop_index(
        op.f("ix_registro_facturacion_emisor_nif"), table_name="registro_facturacion"
    )
    op.drop_index(
        op.f("ix_registro_facturacion_anterior_huella"),
        table_name="registro_facturacion",
    )
    op.drop_index("idx_registro_instalacion_fecha", table_name="registro_facturacion")
    op.drop_index("idx_registro_estado_created", table_name="registro_facturacion")
    op.drop_table("registro_facturacion")
    op.drop_index(op.f("ix_outbox_event_lote_id"), table_name="outbox_event")
    op.drop_index(op.f("ix_outbox_event_instalacion_sif_id"), table_name="outbox_event")
    op.drop_index(op.f("ix_outbox_event_id"), table_name="outbox_event")
    op.drop_index(op.f("ix_outbox_event_estado"), table_name="outbox_event")
    op.drop_index(op.f("ix_outbox_event_created_at"), table_name="outbox_event")
    op.drop_index(
        "idx_outbox_polling_fifo",
        table_name="outbox_event",
        postgresql_where=sa.text("estado = 'pendiente'"),
    )
    op.drop_index("idx_outbox_instalacion_estado", table_name="outbox_event")
    op.drop_table("outbox_event")
    op.drop_index(op.f("ix_lote_envio_instalacion_sif_id"), table_name="lote_envio")
    op.drop_index(op.f("ix_lote_envio_estado"), table_name="lote_envio")
    op.drop_table("lote_envio")
    op.drop_index(op.f("ix_instalacion_sif_obligado_id"), table_name="instalacion_sif")
    op.drop_index(op.f("ix_instalacion_sif_key_hash"), table_name="instalacion_sif")
    op.drop_index(op.f("ix_instalacion_sif_cliente_id"), table_name="instalacion_sif")
    op.drop_index(
        "idx_instalacion_para_worker",
        table_name="instalacion_sif",
        postgresql_where=sa.text("registros_pendientes > 0"),
    )
    op.drop_table("instalacion_sif")
    op.drop_index(op.f("ix_obligado_tributario_nif"), table_name="obligado_tributario")
    op.drop_index(
        op.f("ix_obligado_tributario_colaborador_id"), table_name="obligado_tributario"
    )
    op.drop_table("obligado_tributario")
    op.drop_table("colaborador_social")
    # ### end Alembic commands ###
