"""Actualizar estados validos en check constraint de registro facturacion

Revision ID: a1c56d5ee239
Revises: c96bd430006d
Create Date: 2025-11-21 00:08:13.005848

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a1c56d5ee239"
down_revision: Union[str, None] = "c96bd430006d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
