"""initial setup

Revision ID: c96bd430006d
Revises:
Create Date: 2025-11-20 22:58:40.235433

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c96bd430006d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
